---
train:

    params:
        batch_size: 128
        epoch: 80
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "exp"
        folder: mpii
        model_name: trans6
        step: 10

    data:
        image: "D:\\datasets\\MPIIFaceGaze_GazePoint\\Image"
        label: "D:\\datasets\\MPIIFaceGaze_GazePoint\\Label"
        header: True
        name: mpii
        isFolder: True
        
    pretrain:
        enable: True
        path: "../pre-trained/GazeTR-H-ETH.pt"
        device: 0

    device: 0

    reader: read_data

# dropout = 0
# dim_feed = 512
